# Generated by Django 5.2.12 on 2026-03-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
